pipeline{
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    dockerapp = docker.build("johnnysdocker/guia-jenkins:${env.BUID_ID}", '-f ./Dockerfile ./')
                }
            }
        }

//         stage('Push Docker Image') {
//             steps {
//                 script {
//                     docker.withregistry('https://registry.hub.docker.com', 'dockerhub')
//                 }
//             }
//         }

        stage('Deploy no kubernetes') {
            steps {
                sh 'echo "Executando o comando Kiberclt apply"'
            }
        }
    }
}