pipeline{
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    dockerapp = docker.build("johnnysdocker/guia-jenkins:${env.BUID_ID}", '-f ./Dockerfile ./')
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'johnnys2160') {
                        dockerapp.push('latest')
                        dockerapp.push("${env.BUID_ID}")
                    }
                }
            }
        }

        stage('Deploy no kubernetes') {
            steps {
                sh 'echo "Executando o comando Kiberclt apply"'
            }
        }
    }
}